fix: fallback

diff --git a/.kontinuous/jobs/build/use.yaml b/.kontinuous/jobs/build/use.yaml
--- a/.kontinuous/jobs/build/use.yaml
+++ b/.kontinuous/jobs/build/use.yaml
@@ -18,6 +18,8 @@ runs:
       container.apparmor.security.beta.kubernetes.io/job: unconfined
     seccompProfile:
       type: Unconfined
+    actionSecurityContext:
+      allowPrivilegeEscalation: true
     envFrom:
       - secretRef:
           name: "{{ or $.with.registrySecretRefName $.Values.global.registrySecretRefName }}"
@@ -83,9 +85,10 @@ runs:
       buildkit_addr=$(echo "$buildkit_addr" | sed "s|$prefix_addr|$protocol://$subdomain-$pod_num.$subdomain|")
       {{ end }}
 
-      buildkit_addr="tcp://test-buildkit-service.test-buildkit-service.svc:1235" # debug fail
+      # buildkit_addr="tcp://test-buildkit-service.test-buildkit-service.svc:1235" # enable in debug to emulate service failure
 
-      {{ if (or $.with.buildkitServiceEnabled $.Values.global.buildkitServiceEnabled) }}
+      {{ $buildkitServiceEnabled := (or $.with.buildkitServiceEnabled $.Values.global.buildkitServiceEnabled) }}
+      {{ if $buildkitServiceEnabled }}
       buildctl_cmd="buildctl --addr $buildkit_addr "
       buildctl_options_mtls=""
       if [ -f /buildkit-certs/cert.pem ]; then
@@ -106,45 +109,55 @@ runs:
         export LATEST_TAG=",$IMAGE_PATH:latest"
       fi
 
-      tempfile=/tmp/buildkit-job-output
-      pipe=/tmp/buildkit-pipe-output
-      mkfifo "$pipe"
-      tee "$tempfile" < "$pipe" &
+      runBuildkit() {
+        tempfile=$(mktemp -u)
+        pipe=$(mktemp -u)
+        mkfifo "$pipe"
+        tee "$tempfile" < "$pipe" &
+
+        $buildctl_cmd \
+          $buildctl_options_mtls \
+          build \
+          --frontend dockerfile.v0 \
+          --local context=/workspace/{{ if $.with.context }}/{{ $.with.context }}{{ end }} \
+          --local dockerfile=/workspace{{ if $.with.context }}/{{ $.with.context }}{{ end }} \
+          --opt filename=./{{ or $.with.dockerfile "Dockerfile" }} \
+          --output type=image,\"name=$IMAGE_PATH:{{ or $.with.imageTag $.Values.global.imageTag }},$IMAGE_PATH:{{ $.Values.global.branchSlug32 }}$LATEST_TAG\",push=true \
+          $buildctl_options_cache \
+          {{ if $.with.buildArgs -}}
+          {{- range $key, $val := $.with.buildArgs -}}
+          --opt build-arg:"{{ tpl $key $ }}={{ tpl (print $val) $ }}" \
+          {{ end -}}
+          {{ end -}}
+          {{ if $.with.secrets -}}
+          {{- range $id, $val := $.with.secrets -}}
+          --secret id={{ or $val.id $id }},env=SECRET_{{ $id | upper }} \
+          {{ end -}}
+          {{ end -}}
+          {{ if $.with.target -}}
+          --target="{{ $.with.target }}" \
+          {{ end -}}
+            >"$pipe" 2>&1
+        return $?
+      }
 
       set +e
-      $buildctl_cmd \
-        $buildctl_options_mtls \
-        build \
-        --frontend dockerfile.v0 \
-        --local context=/workspace/{{ if $.with.context }}/{{ $.with.context }}{{ end }} \
-        --local dockerfile=/workspace{{ if $.with.context }}/{{ $.with.context }}{{ end }} \
-        --opt filename=./{{ or $.with.dockerfile "Dockerfile" }} \
-        --output type=image,\"name=$IMAGE_PATH:{{ or $.with.imageTag $.Values.global.imageTag }},$IMAGE_PATH:{{ $.Values.global.branchSlug32 }}$LATEST_TAG\",push=true \
-        $buildctl_options_cache \
-        {{ if $.with.buildArgs -}}
-        {{- range $key, $val := $.with.buildArgs -}}
-        --opt build-arg:"{{ tpl $key $ }}={{ tpl (print $val) $ }}" \
-        {{ end -}}
-        {{ end -}}
-        {{ if $.with.secrets -}}
-        {{- range $id, $val := $.with.secrets -}}
-        --secret id={{ or $val.id $id }},env=SECRET_{{ $id | upper }} \
-        {{ end -}}
-        {{ end -}}
-        {{ if $.with.target -}}
-        --target="{{ $.with.target }}" \
-        {{ end -}}
-          >"$pipe" 2>&1
-
+      runBuildkit
       status=$?
       set -e
 
       if [ "$status" -ne 0 ]; then
         echo "Command failed. Handling error..."
-        cat "$tempfile"
-        exit $status
-      else
-        echo "Command succeeded."
+        if grep -q -e "listing workers for Build: failed to list workers: Unavailable" $tempfile; then
+          echo "buildkit optimized service unavailable, fallback to local build"
+          buildctl_cmd="buildctl-daemonless.sh"
+          buildctl_options_mtls=""
+          runBuildkit
+        else
+          exit $status
+        fi
       fi
+
+      echo "build succeeded."
 
       echo "$IMAGE_PATH:{{ or $.with.imageTag $.Values.global.imageTag }}" >$KONTINUOUS_OUTPUT/IMAGE
